### ISSUE TITLE
###

### ISSUE THREAD

**Issue by xdhauter** [liuchen11/Mesh#1]
请问有没有Java实现此版本的代码？希望跟你聊聊。

**Comment by liuchen11** [comment]
@hautzhangjj 你好，这是C++版本的Visual Studio 2010版本的代码，我已多年不使用Java，Github应该能检索到Java版本的代码

**Comment by xdhauter** [comment]
打扰，麻烦你能不能帮我找找，多谢！！！对C++真的难以掌握，希望你帮我检索下，我没找到相关Java的实现的

**Comment by liuchen11** [comment]
Graphic领域大部分算法都是用C++实现的，这儿有个C#的实现， C#和Java差不多，参见 https://github.com/nobnak/MeshSimplification

**Comment by xdhauter** [comment]
多谢，
